application: timoun-production
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always


- url: /assets
  static_dir: assets
  expiration: "7d"
  secure: always


- url: .*
  script: main.app
  secure: always



libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

# - name: MySQLdb
#   version: "latest"
